In [2]:
import pandas as pd;
import datetime as dt;
import numpy as np;
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import scale
import pickle
from sklearn.ensemble import RandomForestRegressor

testing = pd.read_csv('testing.csv')

#hl = [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
#hl = [100, 100, 100, 100]
hl = [10, 10]
reg = MLPRegressor(solver='adam', hidden_layer_sizes = hl, max_iter = 200000, learning_rate = 'adaptive', learning_rate_init = 0.01) # momentum = 0.5) #activation = 'logistic', 
rfr = RandomForestRegressor()

reg = pickle.load(open('model_2.sav', 'rb'))

In [3]:
training = pd.read_csv('training.csv')
del training['Unnamed: 0']
del training['minute']
#del training['week']
#del training['precipitation']

training_max = training.max()
training_min = training.min()
training_mean = training.mean()

training_norm = (training - training_mean) / (training_max - training_min)

X = training_norm.ix[:, :-1]
y = np.array(training_norm.ix[:, -1:]).ravel()

reg.fit(X, y)

outputfilename = "model_2.sav"

pickle.dump(reg, open(outputfilename, 'wb'))

result = reg.predict(X)

training['predict_travel_time'] = result \
    * (training_max['travel_time'] - training_min['travel_time']) + training_mean['travel_time']

training['error rate'] = abs((training['predict_travel_time'] - training['travel_time']) / training['travel_time'])

error_training = training['error rate'].mean()

#tree

rfr.fit(X, y)

training['rfr_predict_travel_time'] = rfr.predict(X) * (training_max['travel_time'] - training_min['travel_time']) + training_mean['travel_time']

training.to_csv('training_result.csv')

C:\Users\Eric\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  del sys.path[0]

In [3]:
testing = pd.read_csv('testing.csv')
del testing['Unnamed: 0']
del testing['minute']
#del testing['week']
#del testing['precipitation']

testing_max = testing.max()
testing_min = testing.min()
testing_ori = testing
testing_mean = testing.mean()

testing_norm = (testing - training_mean) / (training_max - training_min)
#testing_norm = (testing - testing_mean) / (testing_max - testing_min)

X = testing_norm.ix[:, :-1]

testing['predict_travel_time'] = reg.predict(X) * (training_max['travel_time'] - training_min['travel_time']) + training_mean['travel_time']
#testing['predict_travel_time'] = reg.predict(X) * (testing_max['travel_time'] - testing_min['travel_time']) + testing_mean['travel_time']

testing['error rate'] = abs(testing['predict_travel_time'] - testing['travel_time']) / testing['travel_time']

error_training = testing['error rate'].mean()

testing['rfr_predict_travel_time'] = rfr.predict(X) * (training_max['travel_time'] - training_min['travel_time']) + training_mean['travel_time']
#testing['rfr_predict_travel_time'] = rfr.predict(X) * (testing_max['travel_time'] - testing_min['travel_time']) + testing_mean['travel_time']

testing.to_csv('testing_result.csv')

In [6]:
submission = pd.read_csv('submission.csv')
del submission['Unnamed: 0']
del submission['minute']
del submission['avg_travel_time']
#del submission['travel_time']
#del submission['week']
#del submission['precipitation']

#submission = submission[submission.columns[:-1]]

submission = submission.sort_values(by = ['intersection_id', 'tollgate_id', 'time_window'])

submission_max = submission.max()
submission_min = submission.min()
submission_mean = submission.mean()
submission_norm = submission.copy()

del submission_norm['time_window']

for c in submission_norm.columns:
    submission_norm[c] = (submission_norm[c] - training_mean[c]) / (training_max[c] - training_min[c])

#submission_norm = (submission - submission_mean) / (submission_max - submission_min)


X = submission_norm.ix[:, :]

result = reg.predict(X) \
    * (training_max['travel_time'] - training_min['travel_time']) + training_mean['travel_time']

submission['avg_travel_time'] = result

#submission['rfr_predict_travel_time'] = rfr.predict(X) * (training_max['travel_time'] - training_min['travel_time']) + training_mean['travel_time']

del submission['pressure']
del submission['sea_pressure']
del submission['wind_direction']
del submission['wind_speed']
del submission['temperature']
del submission['rel_humidity']
del submission['precipitation']
del submission['hour']
del submission['week']

submission.loc[submission['intersection_id'] == 1, 'intersection_id'] = 'A'
submission.loc[submission['intersection_id'] == 2, 'intersection_id'] = 'B'
submission.loc[submission['intersection_id'] == 3, 'intersection_id'] = 'C'


submission.to_csv('submission_result.csv')

In [82]:
submission

,intersection_id,tollgate_id,time_window,avg_travel_time
0,A,2,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",78.330948
1,A,2,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",78.330948
2,A,2,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",78.330948
3,A,2,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",79.133664
4,A,2,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",79.133664
5,A,2,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",79.133664
6,A,3,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",94.750993
7,A,3,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",94.750993
8,A,3,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",94.750993
9,A,3,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",94.789423
10,A,3,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",94.789423
11,A,3,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",94.789423
12,B,1,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",105.074364
13,B,1,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",105.074364
14,B,1,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",105.074364
15,B,1,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",107.722825
16,B,1,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",107.722825
17,B,1,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",107.722825
18,B,3,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",115.621774
19,B,3,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",115.621774
20,B,3,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",115.621774
21,B,3,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",115.672745
22,B,3,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",115.672745
23,B,3,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",115.672745
24,C,1,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",197.327244
25,C,1,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",197.327244
26,C,1,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",197.327244
27,C,1,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",198.099914
28,C,1,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",198.099914
29,C,1,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",198.099914
...,...,...,...,...
474,A,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",102.821756
475,A,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",102.821756
476,A,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",102.821756
477,A,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",108.902394
478,A,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",108.902394
479,A,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",108.902394
480,B,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",92.132251
481,B,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",92.132251
482,B,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",92.132251
483,B,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",94.780712
484,B,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",94.780712
485,B,1,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",94.780712
486,B,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",122.904586
487,B,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",122.904586
488,B,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",122.904586
489,B,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",122.464898
490,B,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",122.464898
491,B,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",122.464898
492,C,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",192.375567
493,C,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",192.375567
494,C,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",192.375567
495,C,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",192.060788
496,C,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",192.060788
497,C,1,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",192.060788
498,C,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",144.307847
499,C,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",144.307847
500,C,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",144.307847
501,C,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",143.868159
502,C,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",143.868159
503,C,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",143.868159

In [144]:
submission.columns

Index([u'intersection_id', u'tollgate_id', u'pressure', u'sea_pressure',
       u'wind_direction', u'wind_speed', u'temperature', u'rel_humidity',
       u'precipitation', u'hour', u'week'],
      dtype='object')

In [12]:
training_result = pd.read_csv('training_result.csv')
submission_result = pd.read_csv('submission_result.csv')
testing_result = pd.read_csv('testing_result.csv')

In [54]:
training_1 = training_result.loc[(training_result['intersection_id'] == 1) & \
                    (training_result['week'] == 2) & \
                    (training_result['tollgate_id'] == 2) & \
                    (training_result['hour'] == 8), ['travel_time', 'week', 'tollgate_id', 'hour', 'intersection_id']]

submission_1 = submission_result.loc[(submission_result['intersection_id'] == 1) & \
                    (submission_result['week'] == 2) & \
                    (submission_result['tollgate_id'] == 2) & \
                    (submission_result['hour'] == 8), ['avg_travel_time', 'week', 'tollgate_id', 'hour', 'intersection_id']]

In [57]:
training_result

,Unnamed: 0,intersection_id,tollgate_id,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,hour,week,travel_time,predict_travel_time,error rate,rfr_predict_travel_time
0,0,1,2,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,0,2,58.050000,64.346368,0.108465,59.209292
1,1,1,2,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,1,2,56.870000,58.619323,0.030760,57.034000
2,2,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,1,2,77.740000,70.555403,0.092418,58.344000
3,3,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,2,2,42.640000,71.400103,0.674486,41.093667
4,4,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,2,2,40.173333,71.400103,0.777301,41.093667
5,5,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,3,2,41.920000,72.244802,0.723397,40.118778
6,6,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,3,2,39.430000,72.244802,0.832229,40.118778
7,7,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,4,2,48.130000,73.089501,0.518585,54.489306
8,8,1,2,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,4,2,62.106667,73.089501,0.176838,54.489306
9,9,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,4,2,46.115000,70.770519,0.534653,46.987500
10,10,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,5,2,49.556000,71.615218,0.445137,53.222279
11,11,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,5,2,54.840000,71.615218,0.305894,53.222279
12,12,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,5,2,58.084286,71.615218,0.232953,53.222279
13,13,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,6,2,46.356000,72.459918,0.563118,52.073251
14,14,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,6,2,48.588000,72.459918,0.491313,52.073251
15,15,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,6,2,66.642500,72.459918,0.087293,52.073251
16,16,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,7,2,64.681000,73.304617,0.133325,71.629891
17,17,1,2,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,7,2,85.676000,73.304617,0.144397,71.629891
18,18,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,7,2,58.968889,70.329385,0.192652,58.980257
19,19,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,8,2,81.602857,71.174084,0.127799,74.300259
20,20,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,8,2,80.207857,71.174084,0.112630,74.300259
21,21,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,8,2,63.448462,71.174084,0.121762,74.300259
22,22,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,9,2,78.051176,72.018783,0.077288,71.319500
23,23,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,9,2,69.038333,72.018783,0.043171,71.319500
24,24,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,9,2,69.657143,72.018783,0.033904,71.319500
25,25,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,10,2,78.311538,72.863483,0.069569,71.370172
26,26,1,2,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,10,2,59.411818,72.863483,0.226414,71.370172
27,27,1,2,1000.2,1005.0,215.0,0.7,30.0,77.0,0.0,10,2,75.488889,68.971370,0.086337,70.506465
28,28,1,2,1000.2,1005.0,215.0,0.7,30.0,77.0,0.0,11,2,72.435000,69.816070,0.036156,55.398769
29,29,1,2,1000.2,1005.0,215.0,0.7,30.0,77.0,0.0,11,2,45.942500,69.816070,0.519640,55.398769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24726,24726,3,3,1014.2,1019.2,35.0,3.0,20.4,81.0,0.0,20,7,156.615000,191.801482,0.224669,159.076000
24727,24727,3,3,1014.2,1019.2,35.0,3.0,20.4,81.0,0.0,21,7,151.080000,192.871031,0.276615,148.107000
24728,24728,3,3,1014.2,1019.2,35.0,3.0,20.4,81.0,0.0,22,7,121.350000,192.830942,0.589048,132.413000
24729,24729,3,3,1015.6,1020.6,35.0,2.1,20.1,80.0,0.0,23,7,261.920000,187.693719,0.283393,220.344000
24730,24730,3,3,1015.6,1020.6,35.0,2.1,20.1,80.0,0.0,0,1,184.640000,160.804870,0.129090,177.732000
24731,24731,3,3,1013.7,1018.7,109.0,1.1,20.9,79.0,0.0,8,1,198.635000,166.009212,0.164250,186.191500
24732,24732,3,3,1013.7,1018.7,109.0,1.1,20.9,79.0,0.0,9,1,218.180000,167.338932,0.233024,196.204000
24733,24733,3,3,1013.7,1018.7,109.0,1.1,20.9,79.0,0.0,10,1,220.200000,168.668653,0.234021,194.664000
24734,24734,3,3,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,10,1,149.870000,167.407010,0.117015,145.286667
24735,24735,3,3,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,12,1,104.380000,170.066451,0.629301,135.071967
24736,24736,3,3,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,12,1,142.400000,170.066451,0.194287,135.071967
24737,24737,3,3,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,12,1,149.150000,170.066451,0.140238,135.071967
24738,24738,3,3,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,13,1,169.183333,171.396171,0.013080,162.171333
24739,24739,3,3,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,13,1,149.207500,172.592566,0.156728,151.535155
24740,24740,3,3,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,14,1,150.720000,173.922287,0.153943,166.543871
24741,24741,3,3,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,14,1,191.020000,173.922287,0.089507,166.543871
24742,24742,3,3,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,15,1,126.445000,175.252008,0.385994,151.153556
24743,24743,3,3,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,16,1,171.016667,176.581728,0.032541,211.897639
24744,24744,3,3,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,16,1,311.180000,176.581728,0.432542,211.897639
24745,24745,3,3,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,16,1,198.460000,178.554344,0.100301,186.522000
24746,24746,3,3,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,17,1,122.016667,179.884065,0.474258,178.158278
24747,24747,3,3,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,18,1,173.740000,181.213785,0.043017,378.333067
24748,24748,3,3,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,18,1,526.486667,181.213785,0.655806,378.333067
24749,24749,3,3,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,19,1,101.730000,182.543506,0.794392,227.877250
24750,24750,3,3,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,19,1,187.430000,184.973062,0.013109,192.767550
24751,24751,3,3,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,20,1,209.320000,186.302783,0.109962,198.916017
24752,24752,3,3,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,20,1,194.490000,186.302783,0.042096,198.916017
24753,24753,3,3,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21,1,195.005000,187.632503,0.037807,189.318133
24754,24754,3,3,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21,1,159.440000,187.632503,0.176822,189.318133
24755,24755,3,3,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22,1,185.250000,188.962224,0.020039,172.707500

In [7]:
gb_submission = pd.read_csv('MAPE-0.3653.csv')

In [10]:
gb_submission.sort_values(by = ['intersection_id', 'tollgate_id', 'time_window'])

,intersection_id,tollgate_id,time_window,avg_travel_time
168,A,2,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",114.02
169,A,2,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",114.02
170,A,2,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",114.02
171,A,2,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",114.06
172,A,2,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",114.06
173,A,2,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",114.06
174,A,2,"[2016-10-18 17:00:00,2016-10-18 17:20:00)",125.90
175,A,2,"[2016-10-18 17:20:00,2016-10-18 17:40:00)",125.90
176,A,2,"[2016-10-18 17:40:00,2016-10-18 18:00:00)",125.90
177,A,2,"[2016-10-18 18:00:00,2016-10-18 18:20:00)",126.45
178,A,2,"[2016-10-18 18:20:00,2016-10-18 18:40:00)",126.45
179,A,2,"[2016-10-18 18:40:00,2016-10-18 19:00:00)",126.45
180,A,2,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",123.68
181,A,2,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",123.68
182,A,2,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",123.68
183,A,2,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",124.32
184,A,2,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",124.32
185,A,2,"[2016-10-19 09:40:00,2016-10-19 10:00:00)",124.32
186,A,2,"[2016-10-19 17:00:00,2016-10-19 17:20:00)",112.51
187,A,2,"[2016-10-19 17:20:00,2016-10-19 17:40:00)",112.51
188,A,2,"[2016-10-19 17:40:00,2016-10-19 18:00:00)",112.51
189,A,2,"[2016-10-19 18:00:00,2016-10-19 18:20:00)",112.71
190,A,2,"[2016-10-19 18:20:00,2016-10-19 18:40:00)",112.71
191,A,2,"[2016-10-19 18:40:00,2016-10-19 19:00:00)",112.71
192,A,2,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",123.47
193,A,2,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",123.47
194,A,2,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",123.47
195,A,2,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",124.11
196,A,2,"[2016-10-20 09:20:00,2016-10-20 09:40:00)",124.11
197,A,2,"[2016-10-20 09:40:00,2016-10-20 10:00:00)",124.11
...,...,...,...,...
390,C,3,"[2016-10-22 17:00:00,2016-10-22 17:20:00)",153.16
391,C,3,"[2016-10-22 17:20:00,2016-10-22 17:40:00)",153.16
392,C,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",153.16
393,C,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",154.56
394,C,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",154.56
395,C,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",154.56
396,C,3,"[2016-10-23 08:00:00,2016-10-23 08:20:00)",110.09
397,C,3,"[2016-10-23 08:20:00,2016-10-23 08:40:00)",110.09
398,C,3,"[2016-10-23 08:40:00,2016-10-23 09:00:00)",110.09
399,C,3,"[2016-10-23 09:00:00,2016-10-23 09:20:00)",110.32
400,C,3,"[2016-10-23 09:20:00,2016-10-23 09:40:00)",110.32
401,C,3,"[2016-10-23 09:40:00,2016-10-23 10:00:00)",110.32
402,C,3,"[2016-10-23 17:00:00,2016-10-23 17:20:00)",142.42
403,C,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",142.42
404,C,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",142.42
405,C,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",143.80
406,C,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",143.80
407,C,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",143.80
408,C,3,"[2016-10-24 08:00:00,2016-10-24 08:20:00)",120.44
409,C,3,"[2016-10-24 08:20:00,2016-10-24 08:40:00)",120.44
410,C,3,"[2016-10-24 08:40:00,2016-10-24 09:00:00)",120.44
411,C,3,"[2016-10-24 09:00:00,2016-10-24 09:20:00)",120.85
412,C,3,"[2016-10-24 09:20:00,2016-10-24 09:40:00)",120.85
413,C,3,"[2016-10-24 09:40:00,2016-10-24 10:00:00)",120.85
414,C,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",115.19
415,C,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",115.19
416,C,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",115.19
417,C,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",115.58
418,C,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",115.58
419,C,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",115.58

In [12]:
compare = pd.merge(gb_submission, submission, on=['intersection_id', 'tollgate_id', 'time_window'])

In [14]:
compare.sort_values(by = ['intersection_id', 'tollgate_id', 'time_window'])

,intersection_id,tollgate_id,time_window,avg_travel_time_x,avg_travel_time_y
168,A,2,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",114.02,63.655923
169,A,2,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",114.02,63.655923
170,A,2,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",114.02,63.655923
171,A,2,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",114.06,63.614594
172,A,2,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",114.06,63.614594
173,A,2,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",114.06,63.614594
174,A,2,"[2016-10-18 17:00:00,2016-10-18 17:20:00)",125.90,67.969189
175,A,2,"[2016-10-18 17:20:00,2016-10-18 17:40:00)",125.90,67.969189
176,A,2,"[2016-10-18 17:40:00,2016-10-18 18:00:00)",125.90,67.969189
177,A,2,"[2016-10-18 18:00:00,2016-10-18 18:20:00)",126.45,67.927859
178,A,2,"[2016-10-18 18:20:00,2016-10-18 18:40:00)",126.45,67.927859
179,A,2,"[2016-10-18 18:40:00,2016-10-18 19:00:00)",126.45,67.927859
180,A,2,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",123.68,62.130995
181,A,2,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",123.68,62.130995
182,A,2,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",123.68,62.130995
183,A,2,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",124.32,63.014540
184,A,2,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",124.32,63.014540
185,A,2,"[2016-10-19 09:40:00,2016-10-19 10:00:00)",124.32,63.014540
186,A,2,"[2016-10-19 17:00:00,2016-10-19 17:20:00)",112.51,52.841207
187,A,2,"[2016-10-19 17:20:00,2016-10-19 17:40:00)",112.51,52.841207
188,A,2,"[2016-10-19 17:40:00,2016-10-19 18:00:00)",112.51,52.841207
189,A,2,"[2016-10-19 18:00:00,2016-10-19 18:20:00)",112.71,52.436780
190,A,2,"[2016-10-19 18:20:00,2016-10-19 18:40:00)",112.71,52.436780
191,A,2,"[2016-10-19 18:40:00,2016-10-19 19:00:00)",112.71,52.436780
192,A,2,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",123.47,66.473415
193,A,2,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",123.47,66.473415
194,A,2,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",123.47,66.473415
195,A,2,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",124.11,66.986952
196,A,2,"[2016-10-20 09:20:00,2016-10-20 09:40:00)",124.11,66.986952
197,A,2,"[2016-10-20 09:40:00,2016-10-20 10:00:00)",124.11,66.986952
...,...,...,...,...,...
390,C,3,"[2016-10-22 17:00:00,2016-10-22 17:20:00)",153.16,218.861945
391,C,3,"[2016-10-22 17:20:00,2016-10-22 17:40:00)",153.16,218.861945
392,C,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",153.16,218.861945
393,C,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",154.56,224.407639
394,C,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",154.56,224.407639
395,C,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",154.56,224.407639
396,C,3,"[2016-10-23 08:00:00,2016-10-23 08:20:00)",110.09,174.889120
397,C,3,"[2016-10-23 08:20:00,2016-10-23 08:40:00)",110.09,174.889120
398,C,3,"[2016-10-23 08:40:00,2016-10-23 09:00:00)",110.09,174.889120
399,C,3,"[2016-10-23 09:00:00,2016-10-23 09:20:00)",110.32,176.058683
400,C,3,"[2016-10-23 09:20:00,2016-10-23 09:40:00)",110.32,176.058683
401,C,3,"[2016-10-23 09:40:00,2016-10-23 10:00:00)",110.32,176.058683
402,C,3,"[2016-10-23 17:00:00,2016-10-23 17:20:00)",142.42,175.938641
403,C,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",142.42,175.938641
404,C,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",142.42,175.938641
405,C,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",143.80,177.811184
406,C,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",143.80,177.811184
407,C,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",143.80,177.811184
408,C,3,"[2016-10-24 08:00:00,2016-10-24 08:20:00)",120.44,182.090610
409,C,3,"[2016-10-24 08:20:00,2016-10-24 08:40:00)",120.44,182.090610
410,C,3,"[2016-10-24 08:40:00,2016-10-24 09:00:00)",120.44,182.090610
411,C,3,"[2016-10-24 09:00:00,2016-10-24 09:20:00)",120.85,182.438709
412,C,3,"[2016-10-24 09:20:00,2016-10-24 09:40:00)",120.85,182.438709
413,C,3,"[2016-10-24 09:40:00,2016-10-24 10:00:00)",120.85,182.438709
414,C,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",115.19,191.237649
415,C,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",115.19,191.237649
416,C,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",115.19,191.237649
417,C,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",115.58,191.672115
418,C,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",115.58,191.672115
419,C,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",115.58,191.672115

In [15]:
compare.to_csv('compare.csv')

In [17]:
submission.reset_index()

,index,intersection_id,tollgate_id,time_window,avg_travel_time
0,0,A,2,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",63.655923
1,1,A,2,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",63.655923
2,2,A,2,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",63.655923
3,3,A,2,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",63.614594
4,4,A,2,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",63.614594
5,5,A,2,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",63.614594
6,252,A,2,"[2016-10-18 17:00:00,2016-10-18 17:20:00)",67.969189
7,253,A,2,"[2016-10-18 17:20:00,2016-10-18 17:40:00)",67.969189
8,254,A,2,"[2016-10-18 17:40:00,2016-10-18 18:00:00)",67.969189
9,255,A,2,"[2016-10-18 18:00:00,2016-10-18 18:20:00)",67.927859
10,256,A,2,"[2016-10-18 18:20:00,2016-10-18 18:40:00)",67.927859
11,257,A,2,"[2016-10-18 18:40:00,2016-10-18 19:00:00)",67.927859
12,36,A,2,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",62.130995
13,37,A,2,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",62.130995
14,38,A,2,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",62.130995
15,39,A,2,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",63.014540
16,40,A,2,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",63.014540
17,41,A,2,"[2016-10-19 09:40:00,2016-10-19 10:00:00)",63.014540
18,288,A,2,"[2016-10-19 17:00:00,2016-10-19 17:20:00)",52.841207
19,289,A,2,"[2016-10-19 17:20:00,2016-10-19 17:40:00)",52.841207
20,290,A,2,"[2016-10-19 17:40:00,2016-10-19 18:00:00)",52.841207
21,291,A,2,"[2016-10-19 18:00:00,2016-10-19 18:20:00)",52.436780
22,292,A,2,"[2016-10-19 18:20:00,2016-10-19 18:40:00)",52.436780
23,293,A,2,"[2016-10-19 18:40:00,2016-10-19 19:00:00)",52.436780
24,72,A,2,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",66.473415
25,73,A,2,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",66.473415
26,74,A,2,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",66.473415
27,75,A,2,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",66.986952
28,76,A,2,"[2016-10-20 09:20:00,2016-10-20 09:40:00)",66.986952
29,77,A,2,"[2016-10-20 09:40:00,2016-10-20 10:00:00)",66.986952
...,...,...,...,...,...
474,426,C,3,"[2016-10-22 17:00:00,2016-10-22 17:20:00)",218.861945
475,427,C,3,"[2016-10-22 17:20:00,2016-10-22 17:40:00)",218.861945
476,428,C,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",218.861945
477,429,C,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",224.407639
478,430,C,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",224.407639
479,431,C,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",224.407639
480,210,C,3,"[2016-10-23 08:00:00,2016-10-23 08:20:00)",174.889120
481,211,C,3,"[2016-10-23 08:20:00,2016-10-23 08:40:00)",174.889120
482,212,C,3,"[2016-10-23 08:40:00,2016-10-23 09:00:00)",174.889120
483,213,C,3,"[2016-10-23 09:00:00,2016-10-23 09:20:00)",176.058683
484,214,C,3,"[2016-10-23 09:20:00,2016-10-23 09:40:00)",176.058683
485,215,C,3,"[2016-10-23 09:40:00,2016-10-23 10:00:00)",176.058683
486,462,C,3,"[2016-10-23 17:00:00,2016-10-23 17:20:00)",175.938641
487,463,C,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",175.938641
488,464,C,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",175.938641
489,465,C,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",177.811184
490,466,C,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",177.811184
491,467,C,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",177.811184
492,246,C,3,"[2016-10-24 08:00:00,2016-10-24 08:20:00)",182.090610
493,247,C,3,"[2016-10-24 08:20:00,2016-10-24 08:40:00)",182.090610
494,248,C,3,"[2016-10-24 08:40:00,2016-10-24 09:00:00)",182.090610
495,249,C,3,"[2016-10-24 09:00:00,2016-10-24 09:20:00)",182.438709
496,250,C,3,"[2016-10-24 09:20:00,2016-10-24 09:40:00)",182.438709
497,251,C,3,"[2016-10-24 09:40:00,2016-10-24 10:00:00)",182.438709
498,498,C,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",191.237649
499,499,C,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",191.237649
500,500,C,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",191.237649
501,501,C,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",191.672115
502,502,C,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",191.672115
503,503,C,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",191.672115